import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "next-themes";
import type { ReactNode } from "react";
import { auth } from "@/auth";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({
	weight: ["100", "200", "300", "400", "500", "700", "800", "900"],
	variable: "--font-inter",
	subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
	weight: ["300", "400", "500", "700"],
	variable: "--font-space-grotesk",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Devflow",
	description: "Generated by create next app",
	icons: {
		icon: "/images/site-logo.svg",
	},
};

const RootLayout = async ({ children }: { children: ReactNode }) => {
	const session = await auth();
	return (
		<html lang="en" suppressHydrationWarning>
			<SessionProvider session={session}>
				<body
					className={`${inter.className} ${spaceGrotesk.variable}  antialiased`}
				>
					<header>
						<link
							rel="stylesheet"
							type="text/css"
							href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
						/>
					</header>
					<ThemeProvider
						attribute={"class"}
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
					<Toaster />
				</body>
			</SessionProvider>
		</html>
	);
};

export default RootLayout;
